// <auto-generated />
namespace TicketDataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class update_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201811171459556_update_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
