// <auto-generated />
namespace TicketDataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FullName_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullName_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201906161925394_FullName_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
